id: A2A8AF291
title: 'Devotion That Pierces the Heart: A Prayer to the Omniscient Jigme Lingpa'
type: translation
pechas:
- I20424B48
- I66F0C224
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:43:43.445596
  last_modified_at: 2023-01-04 12:43:43.445612
  collections:
  - Jigme Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  I20424B48/DF0C: '9955'
  I66F0C224/319D: '9955'
